Creates Docs for Google Cloud Storage Source
triggermesh/docs pull request #119
Opened 2021-04-05 15:14 UTC by JeffNeff

2021-04-05 16:05 UTC, JeffNeff commented
relates to https://github.com/triggermesh/frontend/issues/1750

2021-04-07 08:33 UTC, antoineco requested changes
The format is very inconsistent with the template we agreed to use.
Let me know if you want me to take over.

2021-04-07 08:33 UTC, antoineco commented on docs/sources/googlecloudstorage.md
> +```
We decided against having that in documentation pages in #109.

Please see @daceynolan's templates in https://github.com/triggermesh/docs/tree/master/templates/source.

2021-04-07 18:07 UTC, JeffNeff commented
@antoineco all yours :)

2021-04-08 22:14 UTC, merged